export type IconType =
  | 'cartIcon'
  | 'userIcon'
  | 'menuIcon'
  | 'searchIcon'
  | 'starIcon'
  | 'arrowUpIcon'
  | 'arrowRightIcon'
  | 'arrowDownIcon'
  | 'checkCircleIcon'
  | 'checkCircleIconGreen'
  | 'instagramIconLight'
  | 'facebookIconLight'
  | 'youtubeIconLight'
  | 'twitterIconLight';
