export function getInitialAccountFormState(user: any) {
  const format: any = 'bla';

  return {
    firstName: {
      name: 'firstName',
      value: user?.firstName || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.formatFirstName,
    },
    lastName: {
      name: 'lastName',
      value: user?.lastName || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.lastFirstName,
    },
    email: {
      name: 'email',
      value: user?.email || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.email,
    },
    phoneNumber: {
      name: 'phoneNumber',
      value: user?.phoneNumber || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.phoneNumber,
      maxLength: 8,
    },
    city: {
      name: 'city',
      value: user?.city || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.city,
    },
    zipCode: {
      name: 'zipCode',
      value: user?.zipCode || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.zipCode,
      maxLength: 5,
    },
    streetName: {
      name: 'streetName',
      value: user?.streetName || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.streetName,
    },
    doorNumber: {
      name: 'doorNumber',
      value: user?.doorNumber || '',
      required: true,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.doorNumber,
      maxLength: 4,
    },
    doorNumberSuffix: {
      name: 'doorNumberSuffix',
      value: user?.doorNumberSuffix || '',
      required: false,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.doorNumberSuffix,
      maxLength: 2,
    },
    additionalReceiverName: {
      name: 'additionalReceiverName',
      value: user?.additionalReceiverName || '',
      required: false,
      erroMessage: 'bad input',
      isDirty: false,
      isValid: false,
      formatting: format.additionalReceiverName,
    },
  };
}
